// API route to serve the bundled widget.js
// Force rebuild: 2026-02-03
import { NextResponse } from "next/server";

// Import the pre-built widget bundle
// This file is generated by `npm run build:widget`
let WIDGET_BUNDLE: string;
let WIDGET_SIZE_KB: string;

try {
  // Dynamic import to handle case where bundle doesn't exist yet
  const bundle = require("@/lib/widget/dist/widget-bundle");
  WIDGET_BUNDLE = bundle.WIDGET_BUNDLE;
  WIDGET_SIZE_KB = bundle.WIDGET_SIZE_KB;
} catch {
  WIDGET_BUNDLE = `console.error("[Preik] Widget not built. Run 'npm run build:widget' first.");`;
  WIDGET_SIZE_KB = "0";
}

export async function GET() {
  return new NextResponse(WIDGET_BUNDLE, {
    status: 200,
    headers: {
      "Content-Type": "application/javascript; charset=utf-8",
      // Cache for 1 day, stale-while-revalidate for 7 days
      "Cache-Control": "public, max-age=86400, stale-while-revalidate=604800",
      // Allow embedding from any origin
      "Access-Control-Allow-Origin": "*",
      // Size header for debugging
      "X-Widget-Size-KB": WIDGET_SIZE_KB,
    },
  });
}

// Handle CORS preflight
export async function OPTIONS() {
  return new NextResponse(null, {
    status: 204,
    headers: {
      "Access-Control-Allow-Origin": "*",
      "Access-Control-Allow-Methods": "GET, OPTIONS",
      "Access-Control-Allow-Headers": "Content-Type",
    },
  });
}
