#!/usr/bin/env node
// Widget build script using esbuild
import * as esbuild from "esbuild";
import { readFileSync, writeFileSync, mkdirSync } from "fs";
import { fileURLToPath } from "url";
import { dirname, join } from "path";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const rootDir = join(__dirname, "..");

async function buildWidget() {
  const startTime = Date.now();
  console.log("🔨 Building widget...");

  try {
    // Build the widget as an IIFE bundle
    const result = await esbuild.build({
      entryPoints: [join(rootDir, "src/lib/widget/widget.ts")],
      bundle: true,
      minify: true,
      format: "iife",
      target: "es2020",
      write: false,
      sourcemap: false,
      treeShaking: true,
      define: {
        "process.env.NODE_ENV": '"production"',
      },
    });

    if (result.errors.length > 0) {
      console.error("❌ Build errors:", result.errors);
      process.exit(1);
    }

    const code = result.outputFiles[0].text;
    const sizeKB = (code.length / 1024).toFixed(2);

    // Ensure output directory exists
    mkdirSync(join(rootDir, "src/lib/widget/dist"), { recursive: true });

    // Write the bundled code to a file that can be imported
    const outputPath = join(rootDir, "src/lib/widget/dist/widget-bundle.ts");
    writeFileSync(
      outputPath,
      `// Auto-generated by build-widget.mjs - DO NOT EDIT\nexport const WIDGET_BUNDLE = ${JSON.stringify(code)};\nexport const WIDGET_SIZE_KB = ${sizeKB};\n`
    );

    const elapsed = Date.now() - startTime;
    console.log(`✅ Widget built successfully!`);
    console.log(`   Size: ${sizeKB} KB`);
    console.log(`   Time: ${elapsed}ms`);
    console.log(`   Output: ${outputPath}`);

    // Check if size exceeds target
    if (parseFloat(sizeKB) > 50) {
      console.warn(`⚠️  Warning: Widget size (${sizeKB}KB) exceeds 50KB target`);
    }
  } catch (error) {
    console.error("❌ Build failed:", error);
    process.exit(1);
  }
}

buildWidget();
